words = [
    "BLPOP",
    "GETACK",
    "LRANGE",
    "PSYNC",
    "RDB",
    "RPUSH",
    "Replconf",
    "Replicaof",
    "Subcmd",
    "Unwatch",
    "XREAD",
    "aof",
    "appenddirname",
    "appendfilename",
    "appendfsync",
    "appendonly",
    "appendonlydir",
    "capa",
    "dbfilename",
    "everysec",
    "lzf",
    "rdbfile",
    "replid",
]
