words = [
    "BLPOP",
    "GETACK",
    "LRANGE",
    "PSYNC",
    "RDB",
    "RPUSH",
    "Replconf",
    "Replicaof",
    "Subcmd",
    "Unwatch",
    "XREAD",
    "capa",
    "dbfilename",
    "lzf",
    "rdbfile",
    "replid",
]
